server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: record-service
          uri: lb://record-service
          predicates:
            - Path=/api/records/**
        - id: dashboard-service
          uri: lb://dashboard-service
          predicates:
            - Path=/api/dashboard/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  jwt:
    secret: ZorvynFinanceSecretKey2026VeryLongSecretKeyForHMACSHA256Algorithm
    expiration-ms: 86400000
